# Generated by Django 4.2.4 on 2023-08-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('industry', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=100)),
                ('est_date', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField()),
                ('emp_address', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('cmp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_apps.company')),
            ],
        ),
    ]
