# Generated by Django 4.2.4 on 2023-08-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(default='abc', max_length=100),
        ),
    ]
